### ISSUE TITLE
Consider using CSS to darken images

### ISSUE THREAD

**Issue by surisuririsu** [haru-1125/haru-1125.github.io#1]
Instead of setting the img src on toggle, I think you can achieve a similar effect using just CSS.
```css
.character img {
    filter: brightness(0.5) contrast(1.5);
}

.character.owned img {
    filter: unset;
}
```

This way you can reduce the amount of data the app uses to load images, and the amount of work required to add a new p-idol. 😉
